// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV-ufPO_HQQaYmlB1vgo62HCB08Ruqwpc',
    appId: '1:456761078490:web:24c5a422121a545c9d2be3',
    messagingSenderId: '456761078490',
    projectId: 'aura-aec9a',
    authDomain: 'aura-aec9a.firebaseapp.com',
    storageBucket: 'aura-aec9a.firebasestorage.app',
    measurementId: 'G-SENYMP5YZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQGzu-l_hsjdyZDRber-o-Y6iuAw8hhA',
    appId: '1:456761078490:android:b0bc26b1344c74de9d2be3',
    messagingSenderId: '456761078490',
    projectId: 'aura-aec9a',
    storageBucket: 'aura-aec9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-GnsEhOdDiwAoi7GXdVqz-HB7f0CePDs',
    appId: '1:456761078490:ios:b8dd272469d303019d2be3',
    messagingSenderId: '456761078490',
    projectId: 'aura-aec9a',
    storageBucket: 'aura-aec9a.firebasestorage.app',
    iosBundleId: 'com.example.manhattanMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-GnsEhOdDiwAoi7GXdVqz-HB7f0CePDs',
    appId: '1:456761078490:ios:b8dd272469d303019d2be3',
    messagingSenderId: '456761078490',
    projectId: 'aura-aec9a',
    storageBucket: 'aura-aec9a.firebasestorage.app',
    iosBundleId: 'com.example.manhattanMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV-ufPO_HQQaYmlB1vgo62HCB08Ruqwpc',
    appId: '1:456761078490:web:db785b8e464bbc1a9d2be3',
    messagingSenderId: '456761078490',
    projectId: 'aura-aec9a',
    authDomain: 'aura-aec9a.firebaseapp.com',
    storageBucket: 'aura-aec9a.firebasestorage.app',
    measurementId: 'G-S67B2DJXG6',
  );
}
